return {
  { "lukas-reineke/indent-blankline.nvim",
    config = function() require('cwebster.indentline').setup() end,
  },
  {
    "kevinhwang91/nvim-hlslens",
    config = function() require('cwebster.ui.hlslens').setup() end,
    dependencies = {
      "petertriho/nvim-scrollbar",
        config = function() require('cwebster.ui.scrollbar').setup() end,
    }
  },
  {
    "lewis6991/gitsigns.nvim",
    dependencies = {"nvim-lua/plenary.nvim"},
    config = function() require('cwebster.ui.gitsigns').setup() end,
  },
  {"szw/vim-maximizer", lazy = true, cmd="MaximizerToggle"},
  {
    "SmiteshP/nvim-navic",
    config = function() require('cwebster.ui.navic').setup() end,
  },
  {
    "anuvyklack/hydra.nvim",
    config = function() require("cwebster.hydra").setup() end,
  },
  { "folke/which-key.nvim",
    config = function() require("cwebster.whichkey").setup() end,
  },

  { "simrat39/symbols-outline.nvim",
    config = function() require('cwebster.symbols').setup() end,
  },
  { "unblevable/quick-scope" },
  { "kylechui/nvim-surround",
    version = "*",
    config = function() require("cwebster.surround").setup() end,
  },
  { "windwp/nvim-autopairs",
    config = function() require("nvim-autopairs").setup() end,
  },
  {"akinsho/nvim-toggleterm.lua",
    config = function() require('cwebster.neoterm').setup() end,
  },
  { "mfussenegger/nvim-lint",
    config = function() require("cwebster.diagnostics.nvimlint").setup() end,
  },
  { "folke/lsp-trouble.nvim",
    dependencies = "kyazdani42/nvim-web-devicons",
    config = function() require("cwebster.trouble").setup() end,
  },
  { url = "https://git.sr.ht/~whynothugo/lsp_lines.nvim",
    config = function() require("lsp_lines").setup() end,
  },
  { "uga-rosa/ccc.nvim" ,
    config = function() require("cwebster.ui.ccc").setup() end,
  },
  { "almo7aya/openingh.nvim" },
  { "terrortylor/nvim-comment",
    config = function() require("nvim_comment").setup({ comment_empty = false }) end
  },
}
