return {
  {
    "folke/which-key.nvim",
    opts = {
      -- operators = { gc = "Comments", ys = "Surround", yS = "Surround" },
      win = { wo = { winblend = 30 } },
      spec = {
        { "<leader>b", group = "buffer" },
        { "<leader>c", group = "Code Actions" },
        { "<leader>cg", group = "Chat GPT" },
        { "<leader>cl", group = "LSP Actions" },
        { "<leader>d", group = "debug" },
        { "<leader>f", group = "find" },
        { "<leader>g", group = "git" },
        { "<leader>gh", group = "hunks" },
        { "<leader>h", group = "help" },
        { "<leader>s", group = "search" },
        { "<leader>t", group = "testing" },
        { "<leader>x", group = "LSP Diagnostics" },
        { "g", group = "goto" },
        { "gz", group = "zettle" },
        { "gzB", desc = "Id of backlink" },
        { "gzZ", desc = "Insert ID" },
        { "gz[", desc = "Prev Link" },
        { "gz]", desc = "Next Link" },
        { "gzb", desc = "Backlinks" },
        { "gzn", desc = "New" },
        { "gzs", desc = "Start server" },
        { "gzt", desc = "Find/insert tags" },
        { "gzz", desc = "Find/create" },
      },
    },
  },
}
